import { useSelector, useDispatch } from 'react-redux'
import {
  login,
  signup,
  logout,
  verifyEmail,
  resendVerificationCode,
  requestPasswordReset,
  resetPassword,
  updateName,
  changePassword,
  deleteAccount,
  clearError,
  clearNameError,
  clearPasswordError,
  clearDeleteError,
  setResetStep,
  resetResetFlow,
} from '@/store/slices/authSlice'

export function useAuth() {
  const dispatch = useDispatch()
  const {
    isAuthenticated,
    user,
    loading,
    error,
    nameLoading,
    nameError,
    passwordLoading,
    passwordError,
    deleteLoading,
    deleteError,
    resetFlow,
  } = useSelector((s) => s.auth)

  return {
    isAuthenticated,
    user,
    loading,
    error,
    nameLoading,
    nameError,
    passwordLoading,
    passwordError,
    deleteLoading,
    deleteError,
    resetFlow,
    login: (email, password) => dispatch(login({ email, password })),
    signup: (name, email, password) => dispatch(signup({ name, email, password })),
    logout: () => dispatch(logout()),
    verifyEmail: (code) => dispatch(verifyEmail({ code })),
    resendVerificationCode: (email) => dispatch(resendVerificationCode({ email })),
    requestPasswordReset: (email) => dispatch(requestPasswordReset({ email })),
    resetPassword: (code, newPassword, confirmPassword) => dispatch(resetPassword({ code, newPassword, confirmPassword })),
    updateName: (name) => dispatch(updateName({ name })),
    changePassword: (currentPassword, newPassword) => dispatch(changePassword({ currentPassword, newPassword })),
    deleteAccount: (password) => dispatch(deleteAccount({ password })),
    clearError: () => dispatch(clearError()),
    clearNameError: () => dispatch(clearNameError()),
    clearPasswordError: () => dispatch(clearPasswordError()),
    clearDeleteError: () => dispatch(clearDeleteError()),
    setResetStep: (step) => dispatch(setResetStep(step)),
    resetResetFlow: () => dispatch(resetResetFlow()),
  }
}
